// Copyright 2025-2026 Stanislav Senotrusov
//
// This work is dual-licensed under the Apache License, Version 2.0
// and the MIT License. Refer to the LICENSE file in the top-level directory
// for the full license terms.
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

package main

import (
	"bufio"
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
)

func main() {
	// Parse CLI argument for database name
	dbNameFlag := flag.String("d", "", "Database name (overrides PGDATABASE env variable)")
	flag.Parse()

	// Determine database name (CLI arg takes precedence over environment variable)
	dbName := *dbNameFlag
	if dbName == "" {
		dbName = os.Getenv("PGDATABASE")
	}
	if dbName == "" {
		log.Fatal("Error: database name must be provided via -d flag or PGDATABASE environment variable")
	}

	// Emit the markdown section containing the redacted SQL schema dump.
	fmt.Printf("**Database schema for %s**\n", dbName)
	fmt.Println("```sql")
	fmt.Println("-- NOTE: This database schema is intentionally redacted for brevity. Sequences, ownership, text search configuration, and metadata have been stripped. Do not suggest adding missing sequences or default nextval values.")

	// Dump only the pre-data schema
	cmd := exec.Command("pg_dump", "--schema-only", "--section=pre-data", "--no-owner", "--no-privileges", dbName)

	// Capture stdout using a pipe
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		log.Fatalf("Failed to create stdout pipe: %v", err)
	}

	// Route stderr to os.Stderr to see any underlying pg_dump errors
	cmd.Stderr = os.Stderr

	if err := cmd.Start(); err != nil {
		log.Fatalf("Failed to start pg_dump: %v", err)
	}

	// Create a scanner to read the output line by line
	scanner := bufio.NewScanner(stdout)

	// Increase scanner buffer size to 1MB to handle potentially long lines generated by pg_dump
	buf := make([]byte, 0, 64*1024)
	scanner.Buffer(buf, 1024*1024)

	// State variable to track multiline deletions (like sed '/start/,/;/d')
	inSkipBlock := false

	for scanner.Scan() {
		line := scanner.Text()

		// --- sed '/.../,/;/d' behavior ---
		// If we are already in a block that we're deleting, check if this is the end of the block.
		if inSkipBlock {
			if strings.Contains(line, ";") {
				inSkipBlock = false // Reached the end line, resume printing on the *next* line
			}
			continue // Delete (skip) this line
		}

		// Check if we should start deleting a multiline block
		if strings.HasPrefix(line, "CREATE TEXT SEARCH DICTIONARY") ||
			strings.HasPrefix(line, "CREATE TEXT SEARCH CONFIGURATION") ||
			strings.HasPrefix(line, "ALTER TEXT SEARCH CONFIGURATION") ||
			strings.HasPrefix(line, "CREATE SEQUENCE") ||
			strings.HasPrefix(line, "ALTER SEQUENCE") {

			// If the terminating semicolon is NOT on the same line, start the skip block
			if !strings.Contains(line, ";") {
				inSkipBlock = true
			}
			continue // Delete (skip) the starting line
		}

		// --- grep -vE behavior ---
		// Remove comments and empty lines
		if line == "" || strings.HasPrefix(line, "--") {
			continue
		}

		// Remove specific meta commands
		if strings.HasPrefix(line, "\\restrict") || strings.HasPrefix(line, "\\unrestrict") {
			continue
		}

		// Remove noisy setup commands
		if strings.HasPrefix(line, "SET ") ||
			strings.HasPrefix(line, "SELECT ") ||
			strings.HasPrefix(line, "COMMENT ON ") ||
			strings.HasPrefix(line, "CREATE EXTENSION ") {
			continue
		}

		// --- Single line sed deletion ---
		// Remove lines containing SET DEFAULT nextval

		if strings.HasPrefix(line, "ALTER TABLE ONLY ") &&
			strings.Contains(line, "SET DEFAULT nextval") {
			continue
		}

		// If the line survived all the filters, print it to stdout
		fmt.Println(line)
	}

	if err := scanner.Err(); err != nil {
		log.Fatalf("Error reading pg_dump output: %v", err)
	}

	if err := cmd.Wait(); err != nil {
		log.Fatalf("pg_dump finished with error: %v", err)
	}

	// Close markdown code block
	fmt.Println("```")
}
